MCU = atmega32u4
BOOTLOADER = caterina
LTO_ENABLE 					= yes

CONSOLE_ENABLE			= no
COMMAND_ENABLE  		= no
NKRO_ENABLE					= no
BACKLIGHT_ENABLE		= no
RGBLIGHT_ENABLE			= no
AUDIO_ENABLE				= no
UNICODE_ENABLE			= no
MAGIC_ENABLE				= no

BOOTMAGIC_ENABLE		= yes
# MOUSEKEY_ENABLE			= yes
EXTRAKEY_ENABLE			= yes
SPLIT_KEYBOARD 			= yes
AVR_USE_MINIMAL_PRINTF = yes
