#pragma once
#include "config_common.h"

#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM_PER_KEY

#define ONESHOT_TAP_TOGGLE 10
#define ONESHOT_TIMEOUT 500
#define COMBO_TERM 100
#define COMBO_TERM_PER_COMBO

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// disable shit
#define NO_MUSIC_MODE

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define LAYER_STATE_8BIT
#ifdef OLED_ENABLE
  #define OLED_DISPLAY_128X32
  #define OLED_TIMEOUT 15000
  #define OLED_UPDATE_INTERVAL 250

  #define SPLIT_OLED_ENABLE
  #define SPLIT_LAYER_STATE_ENABLE
  #define SPLIT_MODS_ENABLE

  #ifdef WPM_ENABLE
    #define SPLIT_WPM_ENABLE
  #endif
#endif

